import { useEffect, useState } from 'react';
import http from '../../api/http';
import Modal from '../../components/common/Modal';
const empty = { name: '', email: '', phone: '', password: '', role: 'client' };
export default function AdminUsersPage() {
  const [items,setItems]=useState([]); const [open,setOpen]=useState(false); const [form,setForm]=useState(empty); const [editing,setEditing]=useState(null); const [msg,setMsg]=useState('');
  const load=()=>http.get('/admin/users').then(r=>setItems(r.data)); useEffect(()=>{load();},[]);
  const save=async(e)=>{e.preventDefault(); try{ const payload={...form}; if(editing && !payload.password) delete payload.password; editing?await http.put(`/admin/users/${editing}`,payload):await http.post('/admin/users',payload); setOpen(false); setEditing(null); setForm(empty); load(); }catch(err){setMsg(err.message)}};
  const remove=async(id)=>{if(!confirm('Xóa tài khoản này?'))return; try{await http.delete(`/admin/users/${id}`); load();}catch(err){setMsg(err.message)}};
  return <div><div className="mb-6 flex items-center justify-between"><h1 className="text-3xl font-black">Quản lý tài khoản</h1><button className="btn-primary" onClick={()=>{setForm(empty); setEditing(null); setOpen(true)}}>+ Thêm</button></div>{msg&&<p className="mb-4 rounded-2xl bg-red-50 p-3 text-red-600">{msg}</p>}<div className="overflow-x-auto rounded-3xl bg-white p-5 shadow-lg"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="py-3">Tên</th><th>Email</th><th>SĐT</th><th>Role</th><th></th></tr></thead><tbody>{items.map(u=><tr key={u.id} className="border-b"><td className="py-3 font-bold">{u.name}</td><td>{u.email}</td><td>{u.phone}</td><td><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{u.role}</span></td><td><button className="mr-2 font-bold text-emerald-700" onClick={()=>{setForm({...u,password:''});setEditing(u.id);setOpen(true)}}>Sửa</button><button className="font-bold text-red-600" onClick={()=>remove(u.id)}>Xóa</button></td></tr>)}</tbody></table></div><Modal open={open} title={editing?'Sửa tài khoản':'Thêm tài khoản'} onClose={()=>setOpen(false)}><form onSubmit={save} className="grid gap-4 md:grid-cols-2">{['name','email','phone','password'].map(k=><input key={k} className="admin-input" placeholder={k==='password'&&editing?'Mật khẩu mới (để trống nếu không đổi)':k} type={k==='password'?'password':'text'} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<select className="admin-input md:col-span-2" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="client">client</option><option value="admin">admin</option></select><button className="btn-primary md:col-span-2">Lưu</button></form></Modal></div>
}
