import { useEffect, useState } from 'react';
import http from '../../api/http';
import Modal from '../../components/common/Modal';
const empty = { name: '', description: '', icon: '🏷️' };
export default function AdminCategoriesPage() {
  const [items, setItems] = useState([]); const [form, setForm] = useState(empty); const [open, setOpen] = useState(false); const [editing, setEditing] = useState(null); const [message, setMessage] = useState('');
  const load = () => http.get('/admin/categories').then((r) => setItems(r.data)); useEffect(() => { load(); }, []);
  const save = async (e) => { e.preventDefault(); try { editing ? await http.put(`/admin/categories/${editing}`, form) : await http.post('/admin/categories', form); setOpen(false); setEditing(null); setForm(empty); load(); } catch (err) { setMessage(err.message); } };
  const remove = async (id) => { if (!confirm('Xóa danh mục này?')) return; try { await http.delete(`/admin/categories/${id}`); load(); } catch (err) { setMessage(err.message); } };
  return <div><div className="mb-6 flex items-center justify-between"><h1 className="text-3xl font-black">Quản lý danh mục</h1><button className="btn-primary" onClick={() => { setForm(empty); setEditing(null); setOpen(true); }}>+ Thêm</button></div>{message && <p className="mb-4 rounded-2xl bg-red-50 p-3 text-red-600">{message}</p>}<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{items.map((item) => <div key={item.id} className="rounded-3xl bg-white p-6 shadow-lg"><div className="text-4xl">{item.icon}</div><h3 className="mt-4 text-xl font-black">{item.name}</h3><p className="mt-2 text-sm text-slate-500">{item.description}</p><div className="mt-4 flex gap-2"><button className="btn-secondary py-2" onClick={() => { setForm(item); setEditing(item.id); setOpen(true); }}>Sửa</button><button className="rounded-2xl bg-red-50 px-4 py-2 font-bold text-red-600" onClick={() => remove(item.id)}>Xóa</button></div></div>)}</div><Modal open={open} title={editing ? 'Sửa danh mục' : 'Thêm danh mục'} onClose={() => setOpen(false)}><form onSubmit={save} className="grid gap-4"><input className="admin-input" placeholder="Tên danh mục" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input className="admin-input" placeholder="Icon" value={form.icon} onChange={(e) => setForm({ ...form, icon: e.target.value })} /><textarea className="admin-input" placeholder="Mô tả" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><button className="btn-primary">Lưu</button></form></Modal></div>;
}
